name: build-and-test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

env:
  LIBERICA_URL: https://download.bell-sw.com/java/17.0.5+8/bellsoft-jdk17.0.5+8-linux-amd64-full.tar.gz

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: olafurpg/setup-scala@v13
        with:
          java-version: liberica@17=tgz+${{ env.LIBERICA_URL }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python 3 libraries
        run: pip3 install numpy scikit-learn

      - run: sbt -v update compile
      - run: sbt -v test
