name: build-and-test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          java-package: jdk+fx
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python 3 libraries
        run: pip3 install numpy scikit-learn

      - run: sbt -v update compile
      - run: sbt -v test
